scheduler_project/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name ='signup'),
    path('signout/', views.signout, name ='signout'),
    path('signin/', views.signin, name ='signin'),
]

scheduler_project/scheduler_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('scheduler/', include('scheduler.urls')),
    path('ephemeris/', include('ephemeris.urls')),
    path('accounts/', include('accounts.urls')),
]

scheduler_project/templates/_navbar.html
    <ul class="nav nav-tabs">
        <!-- 인증 여부 상관 없이 보임 -->
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/scheduler/">Main</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="/scheduler/month/">April calender</a>
        </li>
        
        <!-- 인증(로그인)된 사용자라면 -->
        {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="/scheduler/create/">New</a>
        </li>
        
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signout' %}">Logout</a>
        </li>


        <!-- 인증(로그인)되지 않은 사용자라면 -->
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signin' %}">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
        </li>
        {% endif %}
    </ul>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

scheduler_project/templates/_style.html
<style>


    .red {color: red}
    .blue {color: blue}
    .container
    {margin: auto;
        padding: 40px, 40px, 40px, 40px ;
        text-align: center;
    }
    
    h1 {text-align: center;
        border-bottom: 2px solid #6CC0FF;
        padding: 15px;
        margin: 20px;
      }

    h2{font-size: 25px}

    td {padding: 1em;}
    th {padding: 1em;}
    table {
        width: 100%;
        table-layout: fixed;
        border: 1px solid #444444;
        border-collapse: collapse;
      }
      th, td {
        border: 1px solid #444444;
      }

    a {color:black;
      text-decoration: none;}

    ol {box-sizing: border-box;
      width: 400px; 
      border: solid #6CC0FF 10px;
      padding: 15px;
      text-align: center;
      margin-left: 50px;}

</style>

scheduler_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    
    <title>Document</title>
</head>
{% include '_style.html' %}
<body>

    {% include '_navbar.html' %}


    {% block content %}
    {% endblock content %}
</body>
</html>